# Generated by Django 4.2.7 on 2023-11-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PUB', 'Published'), ('REJECTED', 'Rejected')], default='DF', max_length=10),
        ),
    ]
